head:
    # 网站图标 多个随机
    favicon: "/img/megumi.png"


img:
    # 头像 多个随机
    avatar: "/img/megumi.png"
    # 首页左边图片 多个随机
    left_pic: 
      - "/img/mountain.png"
    # 首页右边图片 多个随机 (移动端不显示)
    right_pic:
      - "/img/window.jpg"
    # 默认文章背景 多个随机
    post_thumbnail: 
      - "/img/far.jpg"
    # 侧边抽屉头部图片 多个随机
    drawerHeaderBg:
      - "/img/silent.png"

uiux:
    #标语 多个随机
    slogan: ""
    #主色 多个随机
    defaultPrimaryColor: "cyan"
    #强调色 多个随机
    defaultAccentColor: "deepOrange"

#评论 (定义多个 就会显示多个评论框)
comment:
#   duoshuo:
#       shortName: "xxx"
    disqus:
        shortName: "pengchongfu"

#侧边抽屉
Drawer:
    -
      #标题
      title: 首页
      #类型: 站内链接
      type: sitelink
      #链接: 根目录
      href: /
      #图标
      icon: home
    -
      #标题: hr（此处不会显示）
      title: hr
      #类型: 分割线
      type: hr
    -
      #标题: 搜索
      title: 搜索
      #类型: 站内链接
      type: sitelink
      #链接: 搜索功能
      href: /search/
      #图标
      icon: search
    -
      #标题: 联系我
      title: 联系我
      #图标
      icon: contact_phone
      #子目录
      nested: 
        - 
          #标题: Email
          title: Email
          #站外链接
          type: link
          #链接
          href: mailto:pengchongfu@gmail.com
          #图标
          icon: mail_outline
        -
          #标题: Github
          title: Github
          #站外链接
          type: link
          #链接
          href: https://github.com/pengchongfu
          #图标
          icon: 
            #类型: svg (推荐 可以控制颜色)
            type: svg
            #svg内容
            date: '<path d="M941.714 512q0 143.433-83.712 258.011t-216.283 158.574q-15.433 2.853-22.565-3.986t-7.131-17.152v-120.576q0-55.442-29.696-81.152 32.585-3.438 58.587-10.277t53.723-22.272 46.299-37.998 30.281-60.014 11.703-86.016q0-69.157-45.129-117.723 21.138-52.005-4.571-116.553-16.018-5.157-46.299 6.29t-52.553 25.161l-21.723 13.714q-53.138-14.848-109.714-14.848t-109.714 14.848q-9.143-6.29-24.283-15.433t-47.726-22.016-49.152-7.717q-25.161 64.585-3.986 116.553-45.129 48.567-45.129 117.723 0 48.567 11.703 85.723t29.989 60.014 46.007 38.29 53.723 22.272 58.587 10.277q-22.857 20.553-28.014 58.843-11.995 5.705-25.71 8.558t-32.585 2.853-37.413-12.288-31.707-35.73q-10.862-18.286-27.721-29.696t-28.27-13.714l-11.447-1.719q-11.995 0-16.567 2.56t-2.853 6.583 5.157 8.009 7.424 6.839l3.986 2.853q12.581 5.705 24.869 21.723t17.993 29.147l5.705 13.129q7.424 21.723 25.161 35.145t38.29 17.152 39.717 3.986 31.707-2.011l13.129-2.304q0 21.723 0.293 50.871t0.293 30.866q0 10.277-7.424 17.152t-22.857 3.986q-132.571-43.995-216.283-158.574t-83.712-258.011q0-119.442 58.843-220.27t159.707-159.707 220.27-58.843 220.27 58.843 159.707 159.707 58.843 220.27z" p-id="997"></path>'
            #svg viewBox
            viewBox: '0 0 1024 1024'
    -
      title: 友情链接
      icon: people
      nested:
        -
          title: xythu's blog
          type: link
          href: http://xythu.github.io
          icon: face
        -
          title: zhangqythu
          type: link
          href: http://zhangqythu.com
          icon: face

#取色器(在侧边抽屉)
colorPicker: false

#首页工具栏移动端不显示（在首页第2张卡片）
homeToolBar:
  -
    #图标
    icon: "more_vert"
    #子元素
    items:
      -
        #标题: Github
        title: Github
        #站外链接
        type: link
        #链接
        href: https://github.com/pengchongfu
        #图标
        icon: 

#底部
footer:
  # 底部中间(移动端有所不同)  多个随机
  -
    "Copyright © 2016 - 2017 pengchongfu"
  # 底部右间(移动端有所不同)  多个随机
  -
